version: 2

jobs:
  test:
    docker:
      - image: perl:5.24-threaded
      - image: postgres:10-alpine
    environment:
      # Inject APT packaged dependencies.
      PERL5LIB: /usr/lib/x86_64-linux-gnu/perl5/5.24:/usr/share/perl5
      PGHOST: localhost
      PGDATABASE: postgres
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: /tmp/sqlserver2pgsql
    steps:
      - run:
          name: Install debian packages
          command: |
            apt update -y
            apt install -y --no-install-recommends bats git openssh-client postgresql-client
      - checkout
      - run:
          name: Executing tests
          command: prove --verbose

workflows:
  version: 2
  pipeline:
    jobs:
      - test
